//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public int Stt { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
