//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.BID = new HashSet<BID>();
            this.BID_REGISTER = new HashSet<BID_REGISTER>();
            this.HISTORY = new HashSet<HISTORY>();
            this.IMG = new HashSet<IMG>();
        }

        public int IdProduct { get; set; }
        public int IdCate { get; set; }
        public int IdBrand { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        public string NameProduct { get; set; }
        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được để trống")]
        public string Quantity { get; set; }
        [Display(Name = "Trạng thái")]
        [Required(ErrorMessage = "Trạng thái không được để trống")]
        public string Status { get; set; }
        [Display(Name = "Mô tả sản phẩm")]
        [Required(ErrorMessage = "Mô tả sản phẩm không được để trống")]
        public string Desc { get; set; }
        [Display(Name = "Bước giá")]
        [Required(ErrorMessage = "Bước giá không được để trống")]
        public Nullable<int> LowestBid { get; set; }
        [Display(Name = "Giá khởi điểm")]
        [Required(ErrorMessage = "Giá khởi điểm không được để trống")]
        public Nullable<int> StartPrice { get; set; }
        [Display(Name = "Giá mua")]
        [Required(ErrorMessage = "Giá mua không được để trống")]
        public Nullable<int> PriceBuy { get; set; }
        [Display(Name = "Ngày tạo")]
        [Required(ErrorMessage = "Ngày tạo không được để trống")]
        public System.DateTime DateCreate { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "Ngày bắt đầu không được để trống")]
        public System.DateTime StartingDate { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [Required(ErrorMessage = "Ngày kết thúc không được để trống")]
        public System.DateTime EndingDate { get; set; }
        [Display(Name = "Thời gian đặt giá")]
        [Required(ErrorMessage = "Thời gian đặt giá không được để trống")]
        public string Location { get; set; }
        [Display(Name = "Người bán")]
        public Nullable<int> IdOwner { get; set; }
        [Display(Name = "Người mua")]
        public Nullable<int> IdBuyer { get; set; }
        [Display(Name = "Duyệt sản phẩm")]
        public Nullable<bool> StatusBid { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BID> BID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BID_REGISTER> BID_REGISTER { get; set; }
        public virtual BRAND BRAND { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMG> IMG { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
