//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.BID = new HashSet<BID>();
            this.IMG = new HashSet<IMG>();
        }
    
        public int IdProduct { get; set; }
        public int IdCate { get; set; }
        public int IdBrand { get; set; }
        public string NameProduct { get; set; }
        public string Quantity { get; set; }
        public string Status { get; set; }
        public string Desc { get; set; }
        public Nullable<int> LowestBid { get; set; }
        public Nullable<int> StartPrice { get; set; }
        public Nullable<int> PriceBuy { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public Nullable<int> BidTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> IdOwner { get; set; }
        public Nullable<int> IdBuyer { get; set; }
        public Nullable<bool> StatusBid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BID> BID { get; set; }
        public virtual BRAND BRAND { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMG> IMG { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
