//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RANK()
        {
            this.USER = new HashSet<USER>();
        }
    
        public int IdRank { get; set; }
        [Display(Name = "Tên hạng")]
        [Required(ErrorMessage = "Tên hạng không được để trống")]
        public string NameRank { get; set; }
        [Display(Name = "Giá trị")]
        [Required(ErrorMessage = "Giá trị không được để trống")]
        public Nullable<int> Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER { get; set; }
    }
}
